"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import axiosInstance from "@/lib/axios";
import useAuthStore from "@/store/authStore";
import {Shield,Users,FileText,Clock,RefreshCw,Trash2,CheckCircle, Ban, ChevronLeft,ChevronRight} from "lucide-react";

const tabs=[["users","Users"],["posts","Posts"],["stories","Stories"],["subscriptions","Subscriptions"],["scheduled-posts","Scheduled Posts"],["audit-logs","Audit Logs"]];
const AdminPage=()=>{
 const router=useRouter();const user=useAuthStore(s=>s.user);const [stats,setStats]=useState(null);const [tab,setTab]=useState("users");const [items,setItems]=useState([]);const [pagination,setPagination]=useState({page:1,pages:1,total:0});const [filters,setFilters]=useState({search:"",from:"",to:"",status:"",plan:"",verified:"",visibility:""});const [loading,setLoading]=useState(true);
 useEffect(()=>{if(user&&user.role!=="administrator")router.replace("/");},[user,router]);
 const load=async(page=1)=>{setLoading(true);try{const s=await axiosInstance.get("/api/admin/dashboard");setStats(s.data.stats);const q=new URLSearchParams({page:String(page),limit:"12"});Object.entries(filters).forEach(([k,v])=>{if(v)q.set(k,v as string)});let url="/api/admin/"+tab;const r=await axiosInstance.get(url+"?"+q.toString());setItems(r.data.items||[]);setPagination(r.data.pagination||{page:1,pages:1,total:0});}catch(e){console.error(e)}finally{setLoading(false)}};
 useEffect(()=>{if(user?.role==="administrator")load(1)},[tab,user]);useEffect(()=>{const t=setTimeout(()=>{if(user?.role==="administrator")load(1)},350);return()=>clearTimeout(t)},[filters.search,filters.from,filters.to,filters.status,filters.plan,filters.verified,filters.visibility]);
 const mutate=async(path,method="patch",data={})=>{try{await axiosInstance({url:path,method,data});await load(pagination.page)}catch(e:any){alert(e?.response?.data?.message||"Action failed")}};
 if(user?.role!=="administrator")return <div className="min-h-screen flex items-center justify-center">Administrator access required.</div>;
 return <div className="min-h-screen bg-zinc-50 text-zinc-900 p-4 md:p-8">
  <div className="max-w-7xl mx-auto">
   <div className="flex items-center justify-between mb-7"><div><div className="flex gap-2 items-center"><Shield className="text-blue-600"/><h1 className="text-3xl font-bold">Admin Dashboard</h1></div><p className="text-sm text-zinc-500 mt-1">Complete platform management, scheduling monitoring and accountability.</p></div><button onClick={()=>load(pagination.page)} className="p-2 rounded-lg border bg-white"><RefreshCw size={18}/></button></div>
   <div className="grid grid-cols-2 lg:grid-cols-7 gap-3 mb-6">{[["Users",stats?.totalUsers,Users],["Active",stats?.activeUsers,CheckCircle],["Posts",stats?.posts,FileText],["Stories",stats?.stories,Clock],["Subscriptions",stats?.subscriptions,Shield],["Reported",stats?.reportedContent,Ban],["Scheduled",stats?.scheduledPosts,Clock]].map(([label,value,Icon])=><div className="bg-white border rounded-xl p-4" key={label as string}><Icon size={16} className="text-zinc-400 mb-2"/><p className="text-xs text-zinc-500">{label as string}</p><p className="text-2xl font-bold">{value??0}</p></div>)}</div>
   <div className="bg-white border rounded-xl p-2 flex gap-1 overflow-auto mb-4">{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={"px-4 py-2 rounded-lg text-sm whitespace-nowrap "+(tab===id?"bg-black text-white":"hover:bg-zinc-100")}>{label}</button>)}</div>
   <div className="bg-white border rounded-xl p-4 mb-4 grid grid-cols-2 md:grid-cols-6 gap-2">
    <input placeholder="Search keyword" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})} className="col-span-2 border rounded-lg px-3 py-2 text-sm"/>
    <input type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})} className="border rounded-lg px-3 py-2 text-sm"/>
    <input type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})} className="border rounded-lg px-3 py-2 text-sm"/>
    {tab==="users"&&<select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})} className="border rounded-lg px-3 py-2 text-sm"><option value="">Status</option><option>active</option><option>suspended</option><option>deactivated</option></select>}
    {(tab==="subscriptions"||tab==="users")&&<select value={filters.plan} onChange={e=>setFilters({...filters,plan:e.target.value})} className="border rounded-lg px-3 py-2 text-sm"><option value="">Plan</option><option>free</option><option>bronze</option><option>silver</option><option>gold</option></select>}
    {tab==="scheduled-posts"&&<select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})} className="border rounded-lg px-3 py-2 text-sm"><option value="">All scheduling states</option><option value="scheduled">Scheduled</option><option value="published">Published</option><option value="cancelled">Cancelled</option><option value="failed">Failed</option></select>}
   </div>
   <div className="bg-white border rounded-xl overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-zinc-50 border-b"><tr><th className="text-left p-3">Record</th><th className="text-left p-3">Status / Type</th><th className="text-left p-3">Date</th><th className="text-right p-3">Actions</th></tr></thead><tbody>
   {loading?<tr><td colSpan={4} className="p-10 text-center text-zinc-500">Loading…</td></tr>:items.map((x:any)=><tr key={x._id} className="border-b last:border-0"><td className="p-3"><div className="font-semibold">{x.username||x.caption?.slice(0,60)||x.user?.username||x.action||"Record"}</div><div className="text-xs text-zinc-500">{x.email||x.user?.email||x.entityType||x.plan||""}</div></td><td className="p-3"><span className="px-2 py-1 rounded-full bg-zinc-100 text-xs">{x.status||x.scheduleStatus||x.role||x.privacy||"—"}</span></td><td className="p-3 text-zinc-500">{new Date(x.createdAt||x.scheduledAt||Date.now()).toLocaleString("en-IN")}</td><td className="p-3 text-right space-x-2">{tab==="users"&&<><button title="Verify" onClick={()=>mutate("/api/admin/users/"+x._id,"patch",{isVerified:!x.isVerified})} className="p-2 border rounded-lg"><CheckCircle size={15}/></button><button title="Suspend/activate" onClick={()=>mutate("/api/admin/users/"+x._id,"patch",{status:x.status==="active"?"suspended":"active"})} className="p-2 border rounded-lg"><Ban size={15}/></button><button onClick={()=>mutate("/api/admin/users/"+x._id,"delete")} className="p-2 border rounded-lg text-red-600"><Trash2 size={15}/></button></>}{tab==="posts"&&<button onClick={()=>mutate("/api/admin/posts/"+x._id,"delete")} className="p-2 border rounded-lg text-red-600"><Trash2 size={15}/></button>}{tab==="stories"&&<button onClick={()=>mutate("/api/admin/stories/"+x._id,"delete")} className="p-2 border rounded-lg text-red-600"><Trash2 size={15}/></button>}</td></tr>)}</tbody></table></div>
   <div className="flex items-center justify-between p-3 border-t"><span className="text-xs text-zinc-500">Page {pagination.page} of {pagination.pages} · {pagination.total} records</span><div className="flex gap-2"><button disabled={pagination.page<=1} onClick={()=>load(pagination.page-1)} className="p-2 border rounded-lg disabled:opacity-40"><ChevronLeft size={16}/></button><button disabled={pagination.page>=pagination.pages} onClick={()=>load(pagination.page+1)} className="p-2 border rounded-lg disabled:opacity-40"><ChevronRight size={16}/></button></div></div>
   </div>
  </div>
 </div>
}
export default AdminPage;