"use client";
import {useEffect,useState} from "react";
import axiosInstance from "@/lib/axios";
import {CalendarClock,Edit3,XCircle,Save,Plus} from "lucide-react";

export default function ScheduledPostsPage(){
 const [posts,setPosts]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [editing,setEditing]=useState<any>(null);const [form,setForm]=useState({scheduledAt:"",caption:"",location:"",hashtags:""});
 const load=async()=>{setLoading(true);try{const r=await axiosInstance.get("/api/scheduled-posts");setPosts(r.data.posts||[])}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const cancel=async(id:string)=>{await axiosInstance.delete("/api/scheduled-posts/"+id);load()};
 const save=async()=>{if(!editing)return;await axiosInstance.patch("/api/scheduled-posts/"+editing._id,{...form,hashtags:form.hashtags.split(/[ ,]+/).filter(Boolean)});setEditing(null);load()};
 return <div className="min-h-screen bg-zinc-50 p-5 md:p-10"><div className="max-w-5xl mx-auto"><div className="flex items-center justify-between mb-6"><div><div className="flex items-center gap-2"><CalendarClock/><h1 className="text-3xl font-bold">Scheduled Posts</h1></div><p className="text-sm text-zinc-500 mt-1">Maximum 2 future scheduled posts. Scheduled posts stay hidden until publication.</p></div><button className="px-4 py-2 rounded-lg bg-black text-white flex items-center gap-2"><Plus size={16}/>Create from Post composer</button></div>
 <div className="space-y-3">{loading?"Loading…":posts.length===0?<div className="bg-white border rounded-xl p-10 text-center text-zinc-500">No scheduled posts.</div>:posts.map(p=><div key={p._id} className="bg-white border rounded-xl p-4 flex gap-4 items-center"><div className="w-20 h-20 rounded-lg overflow-hidden bg-zinc-100">{p.media?.[0]?.url&&<img src={p.media[0].url} className="w-full h-full object-cover" alt=""/>}</div><div className="flex-1"><div className="font-semibold">{p.caption||"Untitled post"}</div><div className="text-sm text-zinc-500 mt-1">{new Date(p.scheduledAt).toLocaleString("en-IN")} · <span className="capitalize">{p.status}</span></div>{p.lastError&&<div className="text-xs text-red-600 mt-1">{p.lastError}</div>}</div>{p.status==="scheduled"&&<div className="flex gap-2"><button onClick={()=>{setEditing(p);setForm({scheduledAt:new Date(p.scheduledAt).toISOString().slice(0,16),caption:p.caption||"",location:p.location||"",hashtags:(p.hashtags||[]).join(" ")})}} className="p-2 border rounded-lg"><Edit3 size={16}/></button><button onClick={()=>cancel(p._id)} className="p-2 border rounded-lg text-red-600"><XCircle size={16}/></button></div>}</div>)}</div>
 {editing&&<div className="fixed inset-0 bg-black/50 flex items-center justify-center p-4"><div className="bg-white rounded-2xl p-6 w-full max-w-lg"><h2 className="text-xl font-bold mb-4">Edit Scheduled Post</h2><div className="space-y-3"><input type="datetime-local" value={form.scheduledAt} onChange={e=>setForm({...form,scheduledAt:e.target.value})} className="w-full border rounded-lg px-3 py-2"/><textarea value={form.caption} onChange={e=>setForm({...form,caption:e.target.value})} className="w-full border rounded-lg px-3 py-2" rows={4} placeholder="Caption"/><input value={form.hashtags} onChange={e=>setForm({...form,hashtags:e.target.value})} className="w-full border rounded-lg px-3 py-2" placeholder="#hashtags"/><input value={form.location} onChange={e=>setForm({...form,location:e.target.value})} className="w-full border rounded-lg px-3 py-2" placeholder="Location"/></div><div className="flex justify-end gap-2 mt-5"><button onClick={()=>setEditing(null)} className="px-4 py-2 border rounded-lg">Cancel</button><button onClick={save} className="px-4 py-2 bg-black text-white rounded-lg flex items-center gap-2"><Save size={16}/>Save</button></div></div></div>}
 </div></div>
}