"use client";
import {useEffect,useState} from "react";
import axiosInstance from "@/lib/axios";
import {CalendarClock,Edit3,XCircle,Save,Plus} from "lucide-react";
import ScheduledPostCreator from "@/components/insta/ScheduledPostCreator";

export default function ScheduledPostsPage(){
 const [posts,setPosts]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [editing,setEditing]=useState<any>(null);const [creating,setCreating]=useState(false);const [form,setForm]=useState({scheduledAt:"",caption:"",location:"",hashtags:"",taggedUsernames:"",visibility:"public"});
 const load=async()=>{setLoading(true);try{const r=await axiosInstance.get("/api/scheduled-posts");setPosts(r.data.posts||[])}catch(e){console.error(e)}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const cancel=async(id:string)=>{try{await axiosInstance.delete("/api/scheduled-posts/"+id);await load()}catch(e:any){alert(e?.response?.data?.message||"Unable to cancel scheduled post")}};
 const save=async()=>{if(!editing)return;try{await axiosInstance.patch("/api/scheduled-posts/"+editing._id,{...form,hashtags:form.hashtags.split(/[ ,]+/).filter(Boolean),taggedUsernames:form.taggedUsernames.split(/[ ,]+/).filter(Boolean)});setEditing(null);await load()}catch(e:any){alert(e?.response?.data?.message||"Unable to update scheduled post")}};
 return <div className="min-h-screen bg-zinc-50 p-5 md:p-10"><div className="max-w-5xl mx-auto"><div className="flex items-center justify-between mb-6"><div><div className="flex items-center gap-2"><CalendarClock/><h1 className="text-3xl font-bold">Scheduled Posts</h1></div><p className="text-sm text-zinc-500 mt-1">Maximum 2 future scheduled posts. Subscription limits also apply. Scheduled posts stay hidden until publication.</p></div><button type="button" onClick={()=>setCreating(true)} className="px-4 py-2 rounded-lg bg-black text-white flex items-center gap-2"><Plus size={16}/>Create Scheduled Post</button></div>
 <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-5">{["scheduled","published","cancelled","failed"].map(s=><div key={s} className="bg-white border rounded-xl p-4"><p className="text-xs text-zinc-500 capitalize">{s}</p><p className="text-2xl font-bold">{posts.filter(p=>p.status===s).length}</p></div>)}</div>
 <div className="space-y-3">{loading?"Loading…":posts.length===0?<div className="bg-white border rounded-xl p-10 text-center text-zinc-500">No scheduled posts.</div>:posts.map(p=><div key={p._id} className="bg-white border rounded-xl p-4 flex gap-4 items-center"><div className="w-20 h-20 rounded-lg overflow-hidden bg-zinc-100">{p.media?.[0]?.url&&<img src={p.media[0].url} className="w-full h-full object-cover" alt=""/>}</div><div className="flex-1"><div className="font-semibold">{p.caption||"Untitled post"}</div><div className="text-sm text-zinc-500 mt-1">{new Date(p.scheduledAt).toLocaleString("en-IN")} · <span className="capitalize">{p.status}</span></div>{p.lastError&&<div className="text-xs text-red-600 mt-1">{p.lastError}</div>}</div>{p.status==="scheduled"&&<div className="flex gap-2"><button type="button" onClick={()=>{setEditing(p);setForm({scheduledAt:new Date(p.scheduledAt).toISOString().slice(0,16),caption:p.caption||"",location:p.location||"",hashtags:(p.hashtags||[]).join(" "),taggedUsernames:"",visibility:p.visibility||"public"})}} className="p-2 border rounded-lg"><Edit3 size={16}/></button><button type="button" onClick={()=>void cancel(p._id)} className="p-2 border rounded-lg text-red-600"><XCircle size={16}/></button></div>}</div>)}</div>
 {creating&&<ScheduledPostCreator onClose={()=>setCreating(false)} onCreated={load}/>} {editing&&<div className="fixed inset-0 bg-black/50 flex items-center justify-center p-4 z-150"><div className="bg-white rounded-2xl p-6 w-full max-w-lg"><h2 className="text-xl font-bold mb-4">Edit Scheduled Post</h2><div className="space-y-3"><input type="datetime-local" min={new Date(Date.now()+60000).toISOString().slice(0,16)} value={form.scheduledAt} onChange={e=>setForm({...form,scheduledAt:e.target.value})} className="w-full border rounded-lg px-3 py-2"/><textarea value={form.caption} onChange={e=>setForm({...form,caption:e.target.value})} className="w-full border rounded-lg px-3 py-2" rows={4} placeholder="Caption"/><input value={form.hashtags} onChange={e=>setForm({...form,hashtags:e.target.value})} className="w-full border rounded-lg px-3 py-2" placeholder="#hashtags"/><input value={form.taggedUsernames} onChange={e=>setForm({...form,taggedUsernames:e.target.value})} className="w-full border rounded-lg px-3 py-2" placeholder="Tagged usernames"/><input value={form.location} onChange={e=>setForm({...form,location:e.target.value})} className="w-full border rounded-lg px-3 py-2" placeholder="Location"/><select value={form.visibility} onChange={e=>setForm({...form,visibility:e.target.value})} className="w-full border rounded-lg px-3 py-2"><option value="public">Public</option><option value="followers">Followers</option></select></div><div className="flex justify-end gap-2 mt-5"><button type="button" onClick={()=>setEditing(null)} className="px-4 py-2 border rounded-lg">Cancel</button><button type="button" onClick={()=>void save()} className="px-4 py-2 bg-black text-white rounded-lg flex items-center gap-2"><Save size={16}/>Save</button></div></div></div>}
 </div></div>
}